# -*- coding: utf-8 -*-
"""
Created on Thu Jan 14 21:29:29 2021

@author: Hp
"""
LOCAL_CONFIG = {
    "columns": [
'event_name',
'distinct_id',
'event_ts',
'etl_business_ts',
'etl_create_process',
'etl_datasource_id',
'"$ae_session_length"',
'"$app_build_number"',
'"$app_release"',
'"$app_version"',
'"$app_version_string"',
'"$bluetooth_enabled"',
'"$bluetooth_version"',
'"$brand"',
'"$browser"',
'"$browser_version"',
'"$carrier"',
'"$city"',
'"$current_url"',
'"$device"',
'"$device_id"',
'"$duration"',
'"$email"',
'"$event_name"',
'"$google_play_services"',
'"$has_nfc"',
'"$has_telephone"',
'"$initial_referrer"',
'"$initial_referring_domain"',
'"$ios_ifa"',
'"$lib_version"',
'"$manufacturer"',
'"$model"',
'"$os"',
'"$os_version"',
'"$phone"',
'"$radio"',
'"$reason"',
'"$referrer"',
'"$referring_domain"',
'"$region"',
'"$screen_dpi"',
'"$screen_height"',
'"$screen_width"',
'"$search_engine"',
'"$type"',
'"$user_id"',
'"$wifi"',
'"[Koch]App"',
'"[Koch]CampaignId"',
'"[Koch]DeviceId"',
'"[Koch]NetworkId"',
'"[Koch]Offer"',
'"[Koch]Publisher"',
'"[Koch]Tracker"',
'"__mpr"',
'"~tags"',
'"Account ID"',
'"Action"',
'"App Language"',
'"App Locked"',
'"App Rating"',
'"Asset Type"',
'"Campaign"',
'"Campaign Name"',
'"campaign_id"',
'"Captcha Enabled"',
'"Carousel Name"',
'"Cast Name"',
'"Cast Name:"',
'"Cast Role"',
'"Channel Category"',
'"Channel Count"',
'"Channel Is Fav"',
'"Channel Locked"',
'"Channel Name"',
'"Channel Number"',
'"Channels"',
'"Channels Count"',
'"Churn Comment"',
'"Churn Reason"',
'"Clicked Lang"',
'"Comment"',
'"Confirmed Lang"',
'"Content"',
'"costdata"',
'"Country"',
'"Country Code"',
'"Day Name"',
'"Day of Week"',
'"delivery_id"',
'"Device UDID"',
'"Direct Access"',
'"Ease of use"',
'"Email"',
'"_email"',
'"Email Address"',
'"Episode Name"',
'"Episode Number"',
'"Error"',
'"Error Code"',
'"Error Description"',
'"Error Message"',
'"Error Type"',
'"error_type"',
'"Failure Reason"',
'"Failure Type"',
'"FAQ Last Visit"',
'"Features"',
'"Filter Name"',
'"Filter Title"',
'"First Login"',
'"Forgot Password - Mobile Verification - Country Selected"',
'"Forgot Password Last Visit"',
'"From Position"',
'"GUID"',
'"_Guid"',
'"Hour of Day"',
'"HTTP Error Code"',
'"Item Name"',
'"_Item title"',
'"Item Title"',
'"Item Type"',
'"Items Count"',
'"Kernel Version"',
'"Keyword"',
'"Language"',
'"Last Billing Date"',
'"Last Subscription Failure Date"',
'"Last Subscription Type"',
'"Last Verification Attempt"',
'"Last Verification Failure Date"',
'"Last Visit"',
'"List Index"',
'"_Listing Id"',
'"Listing ID"',
'"Locked"',
'"Login Failure Reason"',
'"Login Failure Type"',
'"lptixmd4gx"',
'"Menu Name"',
'"_message"',
'"Message"',
'"message_id"',
'"message_name"',
'"message_type"',
'"Method of Payment"',
'"Mobile Number"',
'"_Mobile number"',
'"Movie Name"',
'"mp_country_code"',
'"mp_device_model"',
'"mp_keyword"',
'"mp_lib"',
'"MSISDN"',
'"Name"',
'"Network Connection"',
'"Old MSISDN"',
'"Operator Name"',
'"PA ID"',
'"Package Name"',
'"Page Last Visit"',
'"Parental Control Level"',
'"Parental Rating"',
'"Payment Method"',
'"Payment Plan"',
'"payment-method"',
'"_phone"',
'"Phone"',
'"Previous Event"',
'"Previous Screen"',
'"Profile Locked"',
'"Profile Name"',
'"Program"',
'"Program Index"',
'"Program Name"',
'"Program Type"',
'"Promotion Title"',
'"Promotion Type"',
'"Public URL"',
'"Question"',
'"Resend From"',
'"Response Error Code"',
'"Response Error Message"',
'"Results Count"',
'"SC - Device ID"',
'"SC - Device Version"',
'"SC - Model Name"',
'"Screen Name"',
'"Season Number"',
'"Section Name"',
'"Selected Audio"',
'"Selected Country"',
'"Selected Date"',
'"Selected Filter"',
'"Selected Level"',
'"Selected Subtitle"',
'"sent_to"',
'"Series Name"',
'"Server"',
'"Slide Number"',
'"Social Media Type"',
'"Sorting Title"',
'"Source"',
'"STB Language"',
'"Store Type"',
'"Subscription Date"',
'"Subscription Last Visit"',
'"Subscription Price"',
'"Subscription Source"',
'"Subscription Type"',
'"Tile Size"',
'"Time Spent"',
'"Title Name"',
'"Trending"',
'"URL"',
'"User ID"',
'"User Name"',
'"utm_campaign"',
'"utm_content"',
'"utm_medium"',
'"utm_source"',
'"utm_term"',
'"Value for money"',
'"Verification Type"',
'"Video Type"',
'"View Type"',
'"Viewed by"',
'"VMX ID"',
'"VOD"',
'"VOD Asset ID"',
'"VOD AssetID"',
'"VOD Duration"',
'"VOD Genre"',
'"VOD Name"',
'"VOD Purchase Type"',
'"VOD Rating"',
'"VOD Type"',
'"VOD Year"',
'"Vs"',
'"Watchlist Type"',
'"Website Version"'

],
"columns_rs": [
'event_name',
'distinct_id',
'event_ts',
'etl_business_ts',
'etl_create_process',
'etl_datasource_id',
'"$ae_session_length"',
'"$app_build_number"',
'"$app_release"',
'"$app_version"',
'"$app_version_string"',
'"$bluetooth_enabled"',
'"$bluetooth_version"',
'"$brand"',
'"$browser"',
'"$browser_version"',
'"$carrier"',
'"$city"',
'"$current_url"',
'"$device"',
'"$device_id"',
'"$duration"',
'"$email"',
'"$event_name"',
'"$google_play_services"',
'"$has_nfc"',
'"$has_telephone"',
'"$initial_referrer"',
'"$initial_referring_domain"',
'"$ios_ifa"',
'"$lib_version"',
'"$manufacturer"',
'"$model"',
'"$os"',
'"$os_version"',
'"$phone"',
'"$radio"',
'"$reason"',
'"$referrer"',
'"$referring_domain"',
'"$region"',
'"$screen_dpi"',
'"$screen_height"',
'"$screen_width"',
'"$search_engine"',
'"$type"',
'"$user_id"',
'"$wifi"',
'"[Koch]App"',
'"[Koch]CampaignId"',
'"[Koch]DeviceId"',
'"[Koch]NetworkId"',
'"[Koch]Offer"',
'"[Koch]Publisher"',
'"[Koch]Tracker"',
'"__mpr"',
'"~tags"',
'"Account ID"',
'"Action"',
'"App Language"',
'"App Locked"',
'"App Rating"',
'"Asset Type"',
'"Campaign"',
'"Campaign Name"',
'"campaign_id"',
'"Captcha Enabled"',
'"Carousel Name"',
'"Cast Name"',
'"Cast Name:"',
'"Cast Role"',
'"Channel Category"',
'"Channel Count"',
'"Channel Is Fav"',
'"Channel Locked"',
'"Channel Name"',
'"Channel Number"',
'"Channels"',
'"Channels Count"',
'"Churn Comment"',
'"Churn Reason"',
'"Clicked Lang"',
'"Comment"',
'"Confirmed Lang"',
'"Content"',
'"costdata"',
'"Country"',
'"Country Code"',
'"Day Name"',
'"Day of Week"',
'"delivery_id"',
'"Device UDID"',
'case when "Direct Access" =\'\' then \'False\' else "Direct Access" end as "Direct Access"',
'"Ease of use"',
'"Email"',
'"_email"',
'"Email Address"',
'"Episode Name"',
'"Episode Number"',
'"Error"',
'"Error Code"',
'"Error Description"',
'"Error Message"',
'"Error Type"',
'"error_type"',
'"Failure Reason"',
'"Failure Type"',
'"FAQ Last Visit"',
'"Features"',
'"Filter Name"',
'"Filter Title"',
'"First Login"',
'"Forgot Password - Mobile Verification - Country Selected"',
'"Forgot Password Last Visit"',
'"From Position"',
'"GUID"',
'"_Guid"',
'"Hour of Day"',
'"HTTP Error Code"',
'"Item Name"',
'"_Item title"',
'"Item Title"',
'"Item Type"',
'"Items Count"',
'"Kernel Version"',
'"Keyword"',
'"Language"',
'"Last Billing Date"',
'"Last Subscription Failure Date"',
'"Last Subscription Type"',
'"Last Verification Attempt"',
'"Last Verification Failure Date"',
'"Last Visit"',
'"List Index"',
'"_Listing Id"',
'"Listing ID"',
'"Locked"',
'"Login Failure Reason"',
'"Login Failure Type"',
'"lptixmd4gx"',
'"Menu Name"',
'"_message"',
'"Message"',
'"message_id"',
'"message_name"',
'"message_type"',
'"Method of Payment"',
'"Mobile Number"',
'"_Mobile number"',
'"Movie Name"',
'"mp_country_code"',
'"mp_device_model"',
'"mp_keyword"',
'"mp_lib"',
'"MSISDN"',
'"Name"',
'"Network Connection"',
'"Old MSISDN"',
'"Operator Name"',
'"PA ID"',
'"Package Name"',
'"Page Last Visit"',
'"Parental Control Level"',
'"Parental Rating"',
'"Payment Method"',
'"Payment Plan"',
'"payment-method"',
'"_phone"',
'"Phone"',
'"Previous Event"',
'"Previous Screen"',
'"Profile Locked"',
'"Profile Name"',
'"Program"',
'"Program Index"',
'"Program Name"',
'"Program Type"',
'"Promotion Title"',
'"Promotion Type"',
'"Public URL"',
'"Question"',
'"Resend From"',
'"Response Error Code"',
'"Response Error Message"',
'"Results Count"',
'"SC - Device ID"',
'"SC - Device Version"',
'"SC - Model Name"',
'"Screen Name"',
'"Season Number"',
'"Section Name"',
'"Selected Audio"',
'"Selected Country"',
'"Selected Date"',
'"Selected Filter"',
'"Selected Level"',
'"Selected Subtitle"',
'"sent_to"',
'"Series Name"',
'"Server"',
'"Slide Number"',
'"Social Media Type"',
'"Sorting Title"',
'"Source"',
'"STB Language"',
'"Store Type"',
'"Subscription Date"',
'"Subscription Last Visit"',
'"Subscription Price"',
'"Subscription Source"',
'"Subscription Type"',
'"Tile Size"',
'"Time Spent"',
'"Title Name"',
'"Trending"',
'"URL"',
'"User ID"',
'"User Name"',
'"utm_campaign"',
'"utm_content"',
'"utm_medium"',
'"utm_source"',
'"utm_term"',
'"Value for money"',
'"Verification Type"',
'"Video Type"',
'"View Type"',
'"Viewed by"',
'"VMX ID"',
'"VOD"',
'"VOD Asset ID"',
'"VOD AssetID"',
'"VOD Duration"',
'"VOD Genre"',
'"VOD Name"',
'"VOD Purchase Type"',
'"VOD Rating"',
'"VOD Type"',
'"VOD Year"',
'"Vs"',
'"Watchlist Type"',
'"Website Version"'

]
}

print("copy data from temp to original table")

cols=','.join(LOCAL_CONFIG['columns'])
cols2=','.join(LOCAL_CONFIG['columns_rs'])
cmd="insert into  public.tbl_raw_mixpanel_custom_jtv_app  ("+cols+") select "+cols2+" from tmp.tbl_raw_mixpanel_custom_jtv_app"
print(cmd)